"""
Django settings for medihouse_backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
from pathlib import Path
from os import path
import environ
import logging
import colorlog
from django.core.management.color import color_style
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from datetime import timedelta

# Read evironment settings
env = environ.Env()
environ.Env.read_env()

# PROJECT DEFAULTS
PROJECT_NAME = env('MEDIHOUSE_PROJECT_NAME', default='MediHouse')
DOMAIN_URL = env('MEDIHOUSE_DOMAIN_URL')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('MEDIHOUSE_SECRET_KEY', default='django-insecure-u3r5w)zs(ui0r@79^@5=80)ric0)e&6k-@_*snd3^unov7_-!7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('MEDIHOUSE_DEBUG', default=True)


# Build paths inside the project like this: PROJECT_PATH / 'subdir'.
# Most of these settings can be overriden by ENV
SETTINGS_PATH = env('SCM_SETTINGS_PATH', default=Path(__file__).resolve().parent)
BASE_PATH = env('SCM_BASE_PATH', default=SETTINGS_PATH.parent)
APP_PATH = env('SCM_APP_PATH', default=BASE_PATH.parent.parent.parent)
LOG_PATH = env('SCM_LOG_PATH', default=path.join(APP_PATH, 'logs'))

# Server data path
# In Ubuntu systems that use NGINX the data path should be in /var/www/html
WWW_PATH = env('SCM_WWW_PATH', default=path.join('/', 'var', 'www', 'html'))
DATA_PATH = path.join(WWW_PATH, 'scm', 'data')

# Media location
MEDIA_ROOT = env('SCM_MEDIA_ROOT', default=path.join(DATA_PATH, 'media'))
MEDIA_URL = env('SCM_MEDIA_URL', default='/media/')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = env('SCM_STATIC_ROOT', default=path.join(DATA_PATH, 'static'))
STATIC_URL = env('SCM_STATIC_URL', default='/static/')
STATICFILES_DIRS = (path.join(SETTINGS_PATH, 'static'),)


# Allowed hosts and internal IPs
ALLOWED_HOSTS = env('MEDIHOUSE_ALLOWED_HOSTS').split(',')
INTERNAL_IPS = env('MEDIHOUSE_INTERNAL_IPS').split(',')
ADMIN_URL = env('MEDIHOUSE_ADMIN_URL', default='admin/')



# Cors Headers settings
CORS_ALLOW_ALL_ORIGINS = env('MEDIHOUSE_CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env('MEDIHOUSE_CORS_ALLOWED_ORIGINS').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medihouse_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medihouse_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if env('MEDIHOUSE_USE_DEV_SQLITE_DB', default=True):
    # Use SQLite database for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
        'erp_tables': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'erp_table.sqlite3',
        },
        'pcm_tables': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': env('MEDIHOUSE_DEFAULT_DB_HOST'),
            'PORT': env('MEDIHOUSE_DEFAULT_DB_PORT'),
            'NAME': env('MEDIHOUSE_DEFAULT_DB_NAME'),
            'USER': env('MEDIHOUSE_DEFAULT_DB_USER'),
            'PASSWORD': env('MEDIHOUSE_DEFAULT_DB_PASSWORD'),
        },
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = env('MEDIHOUSE_LANGUAGE_CODE', default='en-us')

TIME_ZONE = env('MEDIHOUSE_TIME_ZONE', default='UTC')

USE_I18N = env('MEDIHOUSE_USE_I18N', default=True)

USE_L10N = env('MEDIHOUSE_USE_L10N', default=True)

USE_TZ = env('MEDIHOUSE_USE_TZ', default=True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
